---
# tasks file for http
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Start service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent

- name: Create php file with hostname
  ansible.builtin.template:
    src: index.php.j2
    mode: '0o645'
    dest: "/var/www/html/index.php"

- name: Change config nginx
  ansible.builtin.template:
    src: ng_config.j2
    mode: '0o644'
    dest: /etc/nginx/sites-available/default

- name: Restart_nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
