---
# tasks file for users
- name:
  ansible.builtin.user:
      name: user1
      shell: /bin/bash

- name: 
  ansible.posix.authorized_key:
      user: user1
      state: present
      key: "{{ lookup('file', 'files/id_rsa.pub') }}"
